# Generated by Django 6.0.1 on 2026-01-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelike',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_likes', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profilelike',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='from_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='profiles.profile'),
        ),
        migrations.AddConstraint(
            model_name='profilelike',
            constraint=models.UniqueConstraint(fields=('from_profile', 'to_profile'), name='unique_profile_like'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['to_profile', 'from_profile'], name='interaction_to_prof_d3b6ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileview',
            constraint=models.UniqueConstraint(fields=('from_profile', 'to_profile'), name='unique_profile_view_user'),
        ),
    ]
